### ISSUE TITLE
Create new Organization

### ISSUE THREAD

**Issue by seytzhan** [1repo/1repo-web#1]

**Comment by maratkalibek** [comment]
Fields for organization:

0. id or code (string, not auto generated)
1. name
2. description

question here - can we change code later?

**Comment by seytzhan** [comment]
Why not ? 
Also will code be used for url-path ?

**Comment by maratkalibek** [comment]
yes, it will be used.

I got feeling that it is no need to change org code, in that case we can create issues like ORG-123 for the org issue tracker.

**Comment by seytzhan** [comment]
Sounds good, let's try
